import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { initMobileNav } from "./animations/mobile-nav.js";
import { initHeaderScroll } from "./animations/header-scroll.js";
import { initSmoothScroll } from "./animations/smooth-scroll.js";
import { initScrollReveal } from "./animations/scroll-reveal.js";
import { initHeroIntro } from "./animations/hero-intro.js";
import { initHeroGallery } from "./animations/hero-gallery.js";
import { initTextReveal } from "./animations/text-reveal.js";
import { initTextType } from "./animations/text-type.js";
import { initServicesAccordion } from "./animations/services-accordion.js";
import { initServicesShowcase } from "./animations/services-showcase.js";
import { initServicesGallery } from "./animations/services-gallery.js";
import { initResultsCarousel } from "./animations/results-carousel.js";
import { initServiceIntroReveal } from "./animations/service-intro-reveal.js";
import { initServiceProcess } from "./animations/service-process.js";
import { initServiceResultsCarousel } from "./animations/service-results-carousel.js";
import { initProjectsHero } from "./animations/projects-hero.js";
import { initProjectsList } from "./animations/projects-list.js";
import { initCaseStudySnapText } from "./animations/case-study-snap-text.js";
import { initCaseStudySolution } from "./animations/case-study-solution.js";
import { initCaseStudyResults } from "./animations/case-study-results.js";
import { initAboutHero } from "./animations/about-hero.js";
import { initAboutMissionVision } from "./animations/about-mission-vision.js";
import { initAboutHistory } from "./animations/about-history.js";
import { initAboutCertifications } from "./animations/about-certifications.js";
import { initAboutPartners } from "./animations/about-partners.js";
import { initBlogHero } from "./animations/blog-hero.js";
import { initBlogCarousel, initBlogFilters } from "./animations/blog-articles.js";
import { initArticleNav } from "./animations/article-nav.js";
import { initTestimonialCarousel } from "./animations/testimonial-carousel.js";
import { initClientStories } from "./animations/client-stories.js";
import { initContactForm } from "./animations/contact-form.js";
import { initLazyMedia } from "./utils/lazy-load.js";

document.documentElement.classList.remove("no-js");

gsap.registerPlugin(ScrollTrigger);

initSmoothScroll();
initScrollReveal();
initMobileNav();
initHeaderScroll();
initHeroIntro();
initHeroGallery();
initTextReveal();
initTextType();
initServicesAccordion();
initServicesShowcase();
initServicesGallery();
initResultsCarousel();
initServiceIntroReveal();
initServiceProcess();
initServiceResultsCarousel();
initProjectsHero();
initProjectsList();
initCaseStudySnapText();
initCaseStudySolution();
initCaseStudyResults();
initAboutHero();
initAboutMissionVision();
initAboutHistory();
initAboutCertifications();
initAboutPartners();
initBlogHero();
initBlogCarousel();
initBlogFilters();
initArticleNav();
initTestimonialCarousel();
initClientStories();
initContactForm();
initLazyMedia();
